name: ion_openapi
description: OpenAPI 3.x spec generator for ion_router.
homepage: https://github.com/iv-re/ion
repository: https://github.com/iv-re/ion/tree/main/packages/ion_openapi
version: 0.2.1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  ion_router: ^0.1.1
  ion_extra: ^0.2.0
  ion_web: ^0.1.0
  json_schema_builder: ^0.1.6

dev_dependencies:
  checks: ^0.3.1
  test: ^1.25.6
